### PR TITLE
Added New timeout decorator Solves #9

### PR DESCRIPTION
**Pull request by Dawid64**
# Added new timeout decorator

Decorator should work, but needs to be tested on Windows machine.

Therefor it solves the #9 issue

### CODE REVIEW

**Review by MichalRedm — APPROVED** [review]
Looks good!

**Review by adamtms — COMMENTED** [review]
Since it is now multiplatform, I think that the old time restriction decorator should be deleted or marked as deprecated. No point in maintaining 2 functions.

**Review by JaszczurGra — APPROVED** [review]
**Done beautifuly**

**Review by adamtms — APPROVED** [review]
LGTM

**Pull request merged**
