### PR TITLE
17 decorator for disabling printing in some function

### PR DESCRIPTION
**Pull request by adamtms**
I also added decorators for redirecting stdout and stderr

### CODE REVIEW

**Review by Dawid64 — CHANGES_REQUESTED** [review]
Nice work!
Few comments:
- if possible try to avoid or's `|` in type hints, as nice as they look, they got support only on recent versions of python, and it would be better for our library not to crash because of type hints
- I see your intentions about naming convention, but I think it would be clearer if we would create one function `mute` or `silence` that would have parameters: `stdout_target` and `stderr_target`, maybe also with `disable_prints` parameter, to combine this 3 decorators into 1, then consider turning off redirection of std_err, as probably the most common usage will be to disable printing from functions from other libraries
- Also, probably should be fine, but it needs to be checked on windows

**Comment by adamtms** [comment]
> Nice work! Few comments:
> 
> * if possible try to avoid or's `|` in type hints, as nice as they look, they got support only on recent versions of python, and it would be better for our library not to crash because of type hints
> * I see your intentions about naming convention, but I think it would be clearer if we would create one function `mute` or `silence` that would have parameters: `stdout_target` and `stderr_target`, maybe also with `disable_prints` parameter, to combine this 3 decorators into 1, then consider turning off redirection of std_err, as probably the most common usage will be to disable printing from functions from other libraries
> * Also, probably should be fine, but it needs to be checked on windows

I changed | and now it uses Union, which was added in python 3.5 so it should be fine.
I changed the no print decorator to mute, and combined both redirect functions together. Since i wanted there to be an easy option to just disable stdout or stderr by passing None, I do not think that trying to mute prints should have chance to cause stderr to also be redirected.
While errors typically cause python to interrupt execution, warnings do not and it is a nice functionality to be able to redirect them to separate file so I think we should leave this option to the users.

**Comment by Dawid64** [comment]
> I changed | and now it uses Union, which was added in python 3.5 so it should be fine. I changed the no print decorator to mute, and combined both redirect functions together. Since i wanted there to be an easy option to just disable stdout or stderr by passing None, I do not think that trying to mute prints should have chance to cause stderr to also be redirected. While errors typically cause python to interrupt execution, warnings do not and it is a nice functionality to be able to redirect them to separate file so I think we should leave this option to the users.

I see a huge issue now, It's a bit hard and unclear for users to use one of main functionalities: redirecting/ignoring messages, using redirect would require user to put `stderr_target=sys.stderr` in decorator in order to see an error, which I think will usually be the case.  Unless that was your purpose.

Also if you want to separate redirect from mute, would you mind increase mute functionalities, so it also mutes loggers and warnings, as it is probably what we would expect from `mute`, you may ofc call `redirect` set to `None` inside of function, but I would be grateful, if it wouldn't mute errors/exceptions, just everything else.

Also, if you're ready for review you can click `re-request review`

**Review by JaszczurGra — CHANGES_REQUESTED** [review]
Suggestion: 
-Add a decorator for muting all warnings

**Comment by Dawid64** [comment]
I believe I found much better solution for problem with warnings, but without muting exceptions.
Currently, if you use level "warnings" it still doesn't displays error, but if in `redirect` decorator you would use:
```py
try:
    sys.stdout = dest_stdout
    sys.stderr = dest_stderr
    result = __func__(*args, **kwargs)
finally:
    sys.stdout = temp_stdout
    sys.stderr = temp_stderr
```
Then, before exception or error you will change back to default settings, the error will be printed properly, and you want have to catch it in `mute` decorator.

**Review by Dawid64 — APPROVED** [review]
Now it works very well !
One problem is, that is libraries with code in C / not sure about multi processing, it doesn't work (for example for function solver.solve PuLP library solvers), but it is something for another issue. Now I prefer to put it into the main library :D

**Review by JaszczurGra — APPROVED** [review]

**Pull request merged**
